%% Genero i Pianeti
function [Dati] = getPlanet(Name)
    if strcmp(Name, "Terra")
        Dati = struct(  'nome',     Name,...
                        'massa',    5.972e24, ...
                        "pos",      [1.4712e11 0], ...
                        "vel",      [0 2.9789e4], ...
                        "col",      "g"...
                        );
    elseif strcmp(Name, "Luna")
        Dati = struct(  'nome',     Name,...
                        'massa',    7.347e22, ...
                        "pos",      [1.4712e11+3.84e8 0], ...
                        "vel",      [0 -1023+2.9789e4], ...
                        "col",      "k"...
                        );
    elseif strcmp(Name, "Sole")
        Dati = struct(  'nome',     Name,...
                        'massa',    1.989e30, ...
                        "pos",      [0 0], ...
                        "vel",      [0 0], ...
                        "col",      "y"...
                        );
    elseif strcmp(Name, "Mercurio")
        Dati = struct(  'nome',     Name,...
                        'massa',    3.3011e23, ...
                        "pos",      [4.6e10 0], ...
                        "vel",      [0 3.886e4], ...
                        "col",      "cyan"...
                        );
    elseif strcmp(Name, "Venere")
        Dati = struct(  'nome',     Name,...
                        'massa',    4.8675e24, ...
                        "pos",      [1.0748e11 0], ...
                        "vel",      [0 3.479e4], ...
                        "col",      "m"...
                        );
    elseif strcmp(Name, "Marte")
         Dati = struct(  'nome',    Name,...
                        'massa',    6.4185e23, ...
                        "pos",      [-2.2743e+11 0], ...
                        "vel",      [0 -2.4077e4], ...
                        "col",      "r"...
                        );
        
    elseif strcmp(Name, "Giove")
        Dati = struct(  'nome',     Name,...
                        'massa',    1.89819e27,...
                        'pos',      [0, 7.407e11],...
                        'vel',      [-1.2466e4, 0], ...
                        "col",      "b"...
                        );
         %{
    elseif strcmp(Name, "Template")
        Dati = struct(  'nome',     , ...
                        'massa',    , ...
                        'pos',      , ...
                        'vel',      , ...
                        'col'       ...
                        );
    end
         %}
    end

